# Generated by Django 6.0.2 on 2026-02-03 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('warehouse', 'Ombor hodimi'), ('requester', 'Zakas qiluvchi')], default='requester', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Joriy miqdor')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Litr'), ('ml', 'Millilitr'), ('dona', 'Dona'), ('paket', 'Paket'), ('quti', 'Quti'), ('bochka', "Bo'lak")], default='dona', max_length=20, verbose_name="O'lchov birligi")),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, help_text="Bu miqdordan kam bo'lsa ogohlantirish yuboriladi", max_digits=10, verbose_name='Minimum miqdor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.product', verbose_name='Mahsulot')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_orders', to='inventory.telegramuser', verbose_name='Bajargan hodim')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.telegramuser', verbose_name='Zakas qiluvchi')),
            ],
            options={
                'verbose_name': 'Zakas',
                'verbose_name_plural': 'Zakaslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=10, verbose_name='Turi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.order', verbose_name='Zakas')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.telegramuser', verbose_name='Bajargan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
